FROM node:10-slim

MAINTAINER Orta Therox

LABEL "com.github.actions.name"="Danger"
LABEL "com.github.actions.description"="write arguments to the standard output"
LABEL "com.github.actions.icon"="mic"
LABEL "com.github.actions.color"="blue"

ENTRYPOINT ["npx", "--package", "danger", "danger", "ci"]
